# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright (C) 2026 River Games

KERNEL_OBJ = kernel/LineKernel.o kernel/gpt.o kernel/LineRenderer.o third-party/printf.o kernel/str.o kernel/version.o kernel/panic.o kernel/LineInput.o kernel/stack_chk.o kernel/random.o
