# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright (C) 2026 River Games
CC = x86_64-elf-gcc
AS = x86_64-elf-as
LDFLAGS = -T x86_64/linker.ld -ffreestanding -O2 -nostdlib
META_ARCH = x86
ARCH_OBJ = x86_64/boot.o
QEMU = qemu-system-x86_64
