CC = x86_64-elf-gcc
AS = x86_64-elf-as
LDFLAGS = -T x86_64/linker.ld -ffreestanding -O2 -nostdlib
ARCH_OBJ = x86_64/boot.o x86_64/bios_tools.o i386/power.o i386/ps2_keyboard.o i386/serial.o
QEMU = qemu-system-x86_64
