# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright (C) 2026 River Games
META_ARCH_OBJ = x86/bios_tools.o x86/serial.o x86/ps2_keyboard.o x86/power.o x86/gdt.o x86/idt.o x86/interrupts.o x86/timer.o x86/dma.o x86/floppy.o
