# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright (C) 2026 River Games

CC = i686-elf-gcc
AS = i686-elf-as
LDFLAGS = -T i386/linker.ld -ffreestanding -O2 -nostdlib
META_ARCH = x86
ARCH_OBJ = i386/boot.o i386/vga_console.o
QEMU = qemu-system-i386
